// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ObrazovneUstanove.Domain
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class FakeObrazovneUstanoveContext : IObrazovneUstanoveContext
    {
        public System.Data.Entity.DbSet<Ispit> Ispits { get; set; }
        public System.Data.Entity.DbSet<Korisnik> Korisniks { get; set; }
        public System.Data.Entity.DbSet<KorisnikSkolaUloga> KorisnikSkolaUlogas { get; set; }
        public System.Data.Entity.DbSet<Kurs> Kurs { get; set; }
        public System.Data.Entity.DbSet<NaseljnoMjesto> NaseljnoMjestoes { get; set; }
        public System.Data.Entity.DbSet<Obuka> Obukas { get; set; }
        public System.Data.Entity.DbSet<Opstina> Opstinas { get; set; }
        public System.Data.Entity.DbSet<Polaznik> Polazniks { get; set; }
        public System.Data.Entity.DbSet<Skola> Skolas { get; set; }
        public System.Data.Entity.DbSet<StrucnaSprema> StrucnaSpremas { get; set; }
        public System.Data.Entity.DbSet<Sysdiagram> Sysdiagrams { get; set; }
        public System.Data.Entity.DbSet<Uloga> Ulogas { get; set; }

        public FakeObrazovneUstanoveContext()
        {
            Ispits = new FakeDbSet<Ispit>("IspitId");
            Korisniks = new FakeDbSet<Korisnik>("KorisnikId");
            KorisnikSkolaUlogas = new FakeDbSet<KorisnikSkolaUloga>("KorisnikSkolaUlogaId");
            Kurs = new FakeDbSet<Kurs>("KursId");
            NaseljnoMjestoes = new FakeDbSet<NaseljnoMjesto>("NaseljenoMjestoId");
            Obukas = new FakeDbSet<Obuka>("ObukaId");
            Opstinas = new FakeDbSet<Opstina>("OpstinaId");
            Polazniks = new FakeDbSet<Polaznik>("PolaznikId");
            Skolas = new FakeDbSet<Skola>("SkolaId");
            StrucnaSpremas = new FakeDbSet<StrucnaSprema>("StrucnaSpremaId");
            Sysdiagrams = new FakeDbSet<Sysdiagram>("DiagramId");
            Ulogas = new FakeDbSet<Uloga>("UlogaId");

            InitializePartial();
        }

        public int SaveChangesCount { get; private set; }
        public int SaveChanges()
        {
            ++SaveChangesCount;
            return 1;
        }

        public System.Threading.Tasks.Task<int> SaveChangesAsync()
        {
            ++SaveChangesCount;
            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1);
        }

        public System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken)
        {
            ++SaveChangesCount;
            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1, cancellationToken);
        }

        partial void InitializePartial();

        protected virtual void Dispose(bool disposing)
        {
        }

        public void Dispose()
        {
            Dispose(true);
        }
    }
}
// </auto-generated>
