// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ObrazovneUstanove.Domain
{

    public partial interface IObrazovneUstanoveContext : System.IDisposable
    {
        System.Data.Entity.DbSet<Ispit> Ispits { get; set; } // Ispit
        System.Data.Entity.DbSet<Korisnik> Korisniks { get; set; } // Korisnik
        System.Data.Entity.DbSet<KorisnikSkolaUloga> KorisnikSkolaUlogas { get; set; } // KorisnikSkolaUloga
        System.Data.Entity.DbSet<Kurs> Kurs { get; set; } // Kurs
        System.Data.Entity.DbSet<NaseljnoMjesto> NaseljnoMjestoes { get; set; } // NaseljnoMjesto
        System.Data.Entity.DbSet<Obuka> Obukas { get; set; } // Obuka
        System.Data.Entity.DbSet<Opstina> Opstinas { get; set; } // Opstina
        System.Data.Entity.DbSet<Polaznik> Polazniks { get; set; } // Polaznik
        System.Data.Entity.DbSet<Skola> Skolas { get; set; } // Skola
        System.Data.Entity.DbSet<StrucnaSprema> StrucnaSpremas { get; set; } // StrucnaSprema
        System.Data.Entity.DbSet<Sysdiagram> Sysdiagrams { get; set; } // sysdiagrams
        System.Data.Entity.DbSet<Uloga> Ulogas { get; set; } // Uloga

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
    }

}
// </auto-generated>
