// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ObrazovneUstanove.Domain
{

    // Ispit
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class IspitMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Ispit>
    {
        public IspitMap()
            : this("dbo")
        {
        }

        public IspitMap(string schema)
        {
            ToTable(schema + ".Ispit");
            HasKey(x => x.IspitId);

            Property(x => x.IspitId).HasColumnName(@"IspitId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.KursId).HasColumnName(@"KursId").IsRequired().HasColumnType("int");
            Property(x => x.PolaznikId).HasColumnName(@"PolaznikId").IsRequired().HasColumnType("int");
            Property(x => x.DatumOdržavanjaIspita).HasColumnName(@"DatumOdržavanjaIspita").IsRequired().HasColumnType("int");
            Property(x => x.Polozeno).HasColumnName(@"Polozeno").IsOptional().HasColumnType("bit");
            Property(x => x.BrojBodova).HasColumnName(@"BrojBodova").IsOptional().HasColumnType("decimal").HasPrecision(10,2);

            // Foreign keys
            HasRequired(a => a.Kurs).WithMany(b => b.Ispits).HasForeignKey(c => c.KursId).WillCascadeOnDelete(false); // FK_Ispit_Kurs
            HasRequired(a => a.Polaznik).WithMany(b => b.Ispits).HasForeignKey(c => c.PolaznikId).WillCascadeOnDelete(false); // FK_Ispit_Polaznik
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
