// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ObrazovneUstanove.Domain
{

    // Korisnik
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class KorisnikMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Korisnik>
    {
        public KorisnikMap()
            : this("dbo")
        {
        }

        public KorisnikMap(string schema)
        {
            ToTable(schema + ".Korisnik");
            HasKey(x => x.KorisnikId);

            Property(x => x.KorisnikId).HasColumnName(@"KorisnikId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Ime).HasColumnName(@"Ime").IsRequired().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.Prezime).HasColumnName(@"Prezime").IsRequired().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.ImeJednogRoditelja).HasColumnName(@"ImeJednogRoditelja").IsRequired().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.Jmb).HasColumnName(@"Jmb").IsRequired().HasColumnType("nvarchar").HasMaxLength(13);
            Property(x => x.Pol).HasColumnName(@"Pol").IsRequired().IsFixedLength().HasColumnType("nchar").HasMaxLength(1);
            Property(x => x.DatumRodjenja).HasColumnName(@"DatumRodjenja").IsRequired().HasColumnType("date");
            Property(x => x.MjestoRodjenjaOpstinaId).HasColumnName(@"MjestoRodjenjaOpstinaId").IsRequired().HasColumnType("int");
            Property(x => x.PrebivalisteNaseljenoMjestoId).HasColumnName(@"PrebivalisteNaseljenoMjestoId").IsRequired().HasColumnType("int");
            Property(x => x.StrucnaSpremaId).HasColumnName(@"StrucnaSpremaId").IsRequired().HasColumnType("smallint");
            Property(x => x.Zanimanje).HasColumnName(@"Zanimanje").IsRequired().HasColumnType("nvarchar").HasMaxLength(200);

            // Foreign keys
            HasRequired(a => a.NaseljnoMjesto).WithMany(b => b.Korisniks).HasForeignKey(c => c.PrebivalisteNaseljenoMjestoId).WillCascadeOnDelete(false); // FK_Korisnik_NaseljnoMjesto
            HasRequired(a => a.Opstina).WithMany(b => b.Korisniks).HasForeignKey(c => c.MjestoRodjenjaOpstinaId).WillCascadeOnDelete(false); // FK_Korisnik_Opstina
            HasRequired(a => a.StrucnaSprema).WithMany(b => b.Korisniks).HasForeignKey(c => c.StrucnaSpremaId).WillCascadeOnDelete(false); // FK_Korisnik_StrucnaSprema
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
