// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ObrazovneUstanove.Domain
{

    // Korisnik
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class Korisnik
    {
        public int KorisnikId { get; set; } // KorisnikId (Primary key)
        public string Ime { get; set; } // Ime (length: 200)
        public string Prezime { get; set; } // Prezime (length: 200)
        public string ImeJednogRoditelja { get; set; } // ImeJednogRoditelja (length: 200)
        public string Jmb { get; set; } // Jmb (length: 13)
        public string Pol { get; set; } // Pol (length: 1)
        public System.DateTime DatumRodjenja { get; set; } // DatumRodjenja
        public int MjestoRodjenjaOpstinaId { get; set; } // MjestoRodjenjaOpstinaId
        public int PrebivalisteNaseljenoMjestoId { get; set; } // PrebivalisteNaseljenoMjestoId
        public short StrucnaSpremaId { get; set; } // StrucnaSpremaId
        public string Zanimanje { get; set; } // Zanimanje (length: 200)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<KorisnikSkolaUloga> KorisnikSkolaUlogas { get; set; } // KorisnikSkolaUloga.FK_KorisnikSkolaUloga_Korisnik

        // Foreign keys
        public virtual NaseljnoMjesto NaseljnoMjesto { get; set; } // FK_Korisnik_NaseljnoMjesto
        public virtual Opstina Opstina { get; set; } // FK_Korisnik_Opstina
        public virtual StrucnaSprema StrucnaSprema { get; set; } // FK_Korisnik_StrucnaSprema

        public Korisnik()
        {
            KorisnikSkolaUlogas = new System.Collections.Generic.List<KorisnikSkolaUloga>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
