// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ObrazovneUstanove.Domain
{

    // KorisnikSkolaUloga
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class KorisnikSkolaUloga
    {
        public int KorisnikId { get; set; } // KorisnikId
        public int SkolaId { get; set; } // SkolaId
        public int UlogaId { get; set; } // UlogaId
        public System.DateTime AnganzmanOd { get; set; } // AnganzmanOd
        public System.DateTime AnganzmanDo { get; set; } // AnganzmanDo
        public int KorisnikSkolaUlogaId { get; set; } // KorisnikSkolaUlogaId (Primary key)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Obuka> Obukas { get; set; } // Many to many mapping

        // Foreign keys
        public virtual Korisnik Korisnik { get; set; } // FK_KorisnikSkolaUloga_Korisnik
        public virtual Skola Skola { get; set; } // FK_KorisnikSkolaUloga_Skola
        public virtual Uloga Uloga { get; set; } // FK_KorisnikSkolaUloga_Uloga

        public KorisnikSkolaUloga()
        {
            Obukas = new System.Collections.Generic.List<Obuka>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
