// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ObrazovneUstanove.Domain
{

    // NaseljnoMjesto
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class NaseljnoMjestoMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<NaseljnoMjesto>
    {
        public NaseljnoMjestoMap()
            : this("dbo")
        {
        }

        public NaseljnoMjestoMap(string schema)
        {
		            ToTable(schema + ".NaseljnoMjesto");
            HasKey(x => x.NaseljenoMjestoId);

            Property(x => x.NaseljenoMjestoId).HasColumnName(@"NaseljenoMjestoId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Naziv).HasColumnName(@"Naziv").IsRequired().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.OpstinaId).HasColumnName(@"OpstinaId").IsRequired().HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.Opstina).WithMany(b => b.NaseljnoMjestoes).HasForeignKey(c => c.OpstinaId).WillCascadeOnDelete(false); // FK_NaseljnoMjesto_Opstina
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
