// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ObrazovneUstanove.Domain
{

    using System.Linq;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class ObrazovneUstanoveContext : System.Data.Entity.DbContext, IObrazovneUstanoveContext
    {
        public System.Data.Entity.DbSet<Ispit> Ispits { get; set; } // Ispit
        public System.Data.Entity.DbSet<Korisnik> Korisniks { get; set; } // Korisnik
        public System.Data.Entity.DbSet<KorisnikSkolaUloga> KorisnikSkolaUlogas { get; set; } // KorisnikSkolaUloga
        public System.Data.Entity.DbSet<Kur> Kurs { get; set; } // Kurs
        public System.Data.Entity.DbSet<NaseljnoMjesto> NaseljnoMjestoes { get; set; } // NaseljnoMjesto
        public System.Data.Entity.DbSet<Obuka> Obukas { get; set; } // Obuka
        public System.Data.Entity.DbSet<Opstina> Opstinas { get; set; } // Opstina
        public System.Data.Entity.DbSet<Polaznik> Polazniks { get; set; } // Polaznik
        public System.Data.Entity.DbSet<Skola> Skolas { get; set; } // Skola
        public System.Data.Entity.DbSet<StrucnaSprema> StrucnaSpremas { get; set; } // StrucnaSprema
        public System.Data.Entity.DbSet<Sysdiagram> Sysdiagrams { get; set; } // sysdiagrams
        public System.Data.Entity.DbSet<Uloga> Ulogas { get; set; } // Uloga

        static ObrazovneUstanoveContext()
        {
            System.Data.Entity.Database.SetInitializer<ObrazovneUstanoveContext>(null);
        }

        public ObrazovneUstanoveContext()
            : base("Name=ObrazovneUstanoveContext")
        {
            InitializePartial();
        }

        public ObrazovneUstanoveContext(string connectionString)
            : base(connectionString)
        {
            InitializePartial();
        }

        public ObrazovneUstanoveContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
            InitializePartial();
        }

        public ObrazovneUstanoveContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
            InitializePartial();
        }

        public ObrazovneUstanoveContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
            InitializePartial();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new IspitMap());
            modelBuilder.Configurations.Add(new KorisnikMap());
            modelBuilder.Configurations.Add(new KorisnikSkolaUlogaMap());
            modelBuilder.Configurations.Add(new KurMap());
            modelBuilder.Configurations.Add(new NaseljnoMjestoMap());
            modelBuilder.Configurations.Add(new ObukaMap());
            modelBuilder.Configurations.Add(new OpstinaMap());
            modelBuilder.Configurations.Add(new PolaznikMap());
            modelBuilder.Configurations.Add(new SkolaMap());
            modelBuilder.Configurations.Add(new StrucnaSpremaMap());
            modelBuilder.Configurations.Add(new SysdiagramMap());
            modelBuilder.Configurations.Add(new UlogaMap());

            OnModelCreatingPartial(modelBuilder);
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new IspitMap(schema));
            modelBuilder.Configurations.Add(new KorisnikMap(schema));
            modelBuilder.Configurations.Add(new KorisnikSkolaUlogaMap(schema));
            modelBuilder.Configurations.Add(new KurMap(schema));
            modelBuilder.Configurations.Add(new NaseljnoMjestoMap(schema));
            modelBuilder.Configurations.Add(new ObukaMap(schema));
            modelBuilder.Configurations.Add(new OpstinaMap(schema));
            modelBuilder.Configurations.Add(new PolaznikMap(schema));
            modelBuilder.Configurations.Add(new SkolaMap(schema));
            modelBuilder.Configurations.Add(new StrucnaSpremaMap(schema));
            modelBuilder.Configurations.Add(new SysdiagramMap(schema));
            modelBuilder.Configurations.Add(new UlogaMap(schema));
            return modelBuilder;
        }

        partial void InitializePartial();
        partial void OnModelCreatingPartial(System.Data.Entity.DbModelBuilder modelBuilder);
    }
}
// </auto-generated>
