// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ObrazovneUstanove.Domain
{

    // Obuka
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class Obuka
    {
        public int ObukaId { get; set; } // ObukaId (Primary key)
        public int KursId { get; set; } // KursId
        public System.DateTime DatumOd { get; set; } // DatumOd
        public System.DateTime DatumDo { get; set; } // DatumDo
        public decimal Cijena { get; set; } // Cijena

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<KorisnikSkolaUloga> KorisnikSkolaUlogas { get; set; } // Many to many mapping
        public virtual System.Collections.Generic.ICollection<Polaznik> Polazniks { get; set; } // Many to many mapping

        // Foreign keys
        public virtual Kur Kur { get; set; } // FK_Obuka_Kurs

        public Obuka()
        {
            Polazniks = new System.Collections.Generic.List<Polaznik>();
            KorisnikSkolaUlogas = new System.Collections.Generic.List<KorisnikSkolaUloga>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
