// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ObrazovneUstanove.Domain
{

    // Polaznik
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class Polaznik
    {
        public int PolaznikId { get; set; } // PolaznikId (Primary key)
        public string Ime { get; set; } // Ime (length: 200)
        public string Prezime { get; set; } // Prezime (length: 200)
        public string ImeJednogRoditelja { get; set; } // ImeJednogRoditelja (length: 200)
        public System.DateTime DatumRodjenja { get; set; } // DatumRodjenja
        public int MjestoRodjenjaOpstinaId { get; set; } // MjestoRodjenjaOpstinaId
        public int PrebivalisteNaseljenoMjestoId { get; set; } // PrebivalisteNaseljenoMjestoId
        public short StrucnaSpremaId { get; set; } // StrucnaSpremaId
        public string Zanimanje { get; set; } // Zanimanje (length: 200)
        public int SkolaId { get; set; } // SkolaId
        public System.DateTime DatumKreiranja { get; set; } // DatumKreiranja
        public int RadnikIdKreirao { get; set; } // RadnikIdKreirao
        public bool IsDeleted { get; set; } // IsDeleted
        public string Pol { get; set; } // Pol (length: 1)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Ispit> Ispits { get; set; } // Ispit.FK_Ispit_Polaznik
        public virtual System.Collections.Generic.ICollection<Obuka> Obukas { get; set; } // Many to many mapping

        // Foreign keys
        public virtual NaseljnoMjesto NaseljnoMjesto { get; set; } // FK_Polaznik_NaseljnoMjesto
        public virtual Opstina Opstina { get; set; } // FK_Polaznik_Opstina
        public virtual Skola Skola { get; set; } // FK_Polaznik_Skola
        public virtual StrucnaSprema StrucnaSprema { get; set; } // FK_Polaznik_StrucnaSprema

        public Polaznik()
        {
            Ispits = new System.Collections.Generic.List<Ispit>();
            Obukas = new System.Collections.Generic.List<Obuka>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
