// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ObrazovneUstanove.Domain
{

    // Polaznik
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class PolaznikMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Polaznik>
    {
        public PolaznikMap()
            : this("dbo")
        {
        }

        public PolaznikMap(string schema)
        {
		   Map<Polaznik>(t => t.Requires("IsDeleted").HasValue(false)).Ignore(t => t.IsDeleted);

            ToTable(schema + ".Polaznik");
            HasKey(x => x.PolaznikId);

            Property(x => x.PolaznikId).HasColumnName(@"PolaznikId").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Ime).HasColumnName(@"Ime").IsRequired().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.Prezime).HasColumnName(@"Prezime").IsRequired().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.ImeJednogRoditelja).HasColumnName(@"ImeJednogRoditelja").IsOptional().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.DatumRodjenja).HasColumnName(@"DatumRodjenja").IsRequired().HasColumnType("date");
            Property(x => x.MjestoRodjenjaOpstinaId).HasColumnName(@"MjestoRodjenjaOpstinaId").IsRequired().HasColumnType("int");
            Property(x => x.PrebivalisteNaseljenoMjestoId).HasColumnName(@"PrebivalisteNaseljenoMjestoId").IsRequired().HasColumnType("int");
            Property(x => x.StrucnaSpremaId).HasColumnName(@"StrucnaSpremaId").IsRequired().HasColumnType("smallint");
            Property(x => x.Zanimanje).HasColumnName(@"Zanimanje").IsRequired().HasColumnType("nvarchar").HasMaxLength(200);
            Property(x => x.SkolaId).HasColumnName(@"SkolaId").IsRequired().HasColumnType("int");
            Property(x => x.DatumKreiranja).HasColumnName(@"DatumKreiranja").IsRequired().HasColumnType("datetime");
            Property(x => x.RadnikIdKreirao).HasColumnName(@"RadnikIdKreirao").IsRequired().HasColumnType("int");
            Property(x => x.Pol).HasColumnName(@"Pol").IsRequired().IsFixedLength().HasColumnType("nchar").HasMaxLength(1);

            // Foreign keys
            HasRequired(a => a.NaseljnoMjesto).WithMany(b => b.Polazniks).HasForeignKey(c => c.PrebivalisteNaseljenoMjestoId).WillCascadeOnDelete(false); // FK_Polaznik_NaseljnoMjesto
            HasRequired(a => a.Opstina).WithMany(b => b.Polazniks).HasForeignKey(c => c.MjestoRodjenjaOpstinaId).WillCascadeOnDelete(false); // FK_Polaznik_Opstina
            HasRequired(a => a.Skola).WithMany(b => b.Polazniks).HasForeignKey(c => c.SkolaId).WillCascadeOnDelete(false); // FK_Polaznik_Skola
            HasRequired(a => a.StrucnaSprema).WithMany(b => b.Polazniks).HasForeignKey(c => c.StrucnaSpremaId).WillCascadeOnDelete(false); // FK_Polaznik_StrucnaSprema
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
