// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ObrazovneUstanove.Domain
{

    // StrucnaSprema
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class StrucnaSprema
    {
        public short StrucnaSpremaId { get; set; } // StrucnaSpremaId (Primary key)
        public string Naziv { get; set; } // Naziv (length: 200)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Korisnik> Korisniks { get; set; } // Korisnik.FK_Korisnik_StrucnaSprema
        public virtual System.Collections.Generic.ICollection<Polaznik> Polazniks { get; set; } // Polaznik.FK_Polaznik_StrucnaSprema

        public StrucnaSprema()
        {
            Korisniks = new System.Collections.Generic.List<Korisnik>();
            Polazniks = new System.Collections.Generic.List<Polaznik>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
