// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace ObrazovneUstanove.Domain
{

    // Uloga
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.20.1.0")]
    public partial class Uloga
    {
        public int UlogaId { get; set; } // UlogaId (Primary key)
        public string Naziv { get; set; } // Naziv (length: 200)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<KorisnikSkolaUloga> KorisnikSkolaUlogas { get; set; } // KorisnikSkolaUloga.FK_KorisnikSkolaUloga_Uloga

        public Uloga()
        {
            KorisnikSkolaUlogas = new System.Collections.Generic.List<KorisnikSkolaUloga>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
